#!/bin/bash

# If you want to run this as a cron job, change the name below to your user
# name and drop this file into cron.d. Alternatively, you can delete the name
# and append this to your crontab.

@hourly dillon python project_bravo.py
